// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Constants$ReactHooksTemplate = require("./Constants.bs.js");

function Cell(Props) {
  var children = Props.children;
  var last = Props.last;
  var tileColors = /* array */[
    "rgba(238, 228, 218, 0.35)",
    "#eee4da",
    "#ede0c8",
    "#f2b179"
  ];
  var cellStyle = {
    backgroundColor: Caml_array.caml_array_get(tileColors, Math.log2(children) | 0),
    color: "#776e65",
    display: "flex",
    fontFamily: "'Clear Sans', 'Helvetica Neue', Arial, sans-serif",
    fontSize: "10vw",
    fontWeight: "bold",
    height: "20vw",
    width: "20vw",
    borderRadius: Constants$ReactHooksTemplate.borderRadius,
    alignItems: "center",
    justifyContent: "center"
  };
  var cellExtraStyle = {
    marginRight: Constants$ReactHooksTemplate.margin
  };
  return React.createElement("div", {
              style: last ? cellStyle : ReactDOMRe.Style[/* combine */0](cellStyle, cellExtraStyle)
            }, children !== 0 ? String(children) : null);
}

var make = Cell;

exports.make = make;
/* react Not a pure module */
