// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


var borderRadius = "1vw";

var margin = "1.75vw";

exports.borderRadius = borderRadius;
exports.margin = margin;
/* No side effect */
